// Devices
export const DEVICES_ADD = 'DEVICES_ADD'
export const DEVICES_SET_PREVIOUS_MAC = 'DEVICES_SET_PREVIOUS_MAC'

// SETTINGS
export const SETTINGS_CHANGE_SELECTED_DEVICE = 'SETTINGS_CHANGE_SELECTED_DEVICE'
export const SETTINGS_CHANGE_PAGE = 'SETTINGS_CHANGE_PAGE'
export const SETTINGS_SET_LOADING = 'SETTINGS_SET_LOADING'

// NOTIFY
export const UPDATE_NOTIFCATION = 'UPDATE_NOTIFCATION'
